New TMP_DIR

diff --git a/infra/base-images/base-builder/compile b/infra/base-images/base-builder/compile
--- a/infra/base-images/base-builder/compile
+++ b/infra/base-images/base-builder/compile
@@ -51,7 +51,14 @@ export CXXFLAGS="$CFLAGS $CXXFLAGS_EXTRA"
 
 if [[ "$FUZZING_ENGINE" == aflgo ]]; then
 
-  TMP_DIR=$(mktemp -d)
+  TMP_DIR=$WORK/tmp
+  i=0
+  while [ -d $TMP_DIR ]; do
+    TMP_DIR=$WORK/tmp.$i
+    i=$((i + 1))
+  done 
+  mkdir $TMP_DIR
+
   COPY_CFLAGS=$CFLAGS
   COPY_CXXFLAGS=$CXXFLAGS
 
@@ -71,7 +78,8 @@ if [[ "$FUZZING_ENGINE" == aflgo ]]; then
   popd > /dev/null
 
   if [ $(cat $TMP_DIR/BBtargets.txt | wc -l) -eq 0 ]; then
-    echo "No changed source code lines in commit $COMMIT of $PROJECT. Aborting.."
+    echo "No changed source <files> in commit $COMMIT of $PROJECT. Aborting.."
+    rm -rf $TMP_DIR
     exit 1
   fi
 
@@ -101,6 +109,12 @@ if [[ "$FUZZING_ENGINE" == aflgo ]]; then
     chmod +x $SRC/test.sh
   fi
 
+  if ! [ -f $TMP_DIR/Ftargets.txt ]; then
+    echo "No changed source code <lines> in commit $COMMIT of $PROJECT. Aborting.."
+    rm -rf $TMP_DIR
+    exit 1
+  fi
+
   #FILTER BBnames and Fnames
   cat $TMP_DIR/BBnames.txt | rev | cut -d: -f2- | rev | sort | uniq > $TMP_DIR/BBnames2.txt && mv $TMP_DIR/BBnames2.txt $TMP_DIR/BBnames.txt
   cat $TMP_DIR/Fnames.txt | grep -v -e "^__" -e "^asan\." -e "^llvm\." -e "^sancov\." > $TMP_DIR/Fnames2.txt && mv $TMP_DIR/Fnames2.txt $TMP_DIR/Fnames.txt
@@ -108,6 +122,7 @@ if [[ "$FUZZING_ENGINE" == aflgo ]]; then
   echo "---------------------------------------------------------------"
   $SRC/aflgo/scripts/genDistance.sh $OUT $SRC/test.sh $TMP_DIR
   cp $TMP_DIR/distance.cfg.txt $OUT
+  rm -rf $TMP_DIR
 
   CFLAGS="$COPY_CFLAGS -distance=$OUT/distance.cfg.txt"
   CXXFLAGS="$COPY_CXXFLAGS -distance=$OUT/distance.cfg.txt"
